---
platform: linux

image_resource:
	type: docker-image
source:
	repository: node
inputs:
- name: todo-front-resource
outputs: 
- name: todo-front-build-output
run:
  path: sh
  args:
  - -exc
  - |
    cd todo-front-resource
    npm install
    npm run build
    cp -r dist ../todo-front-build-output
    cp Dockerfile ../todo-front-build-output
    echo "Front : build task completed"
